src/NodeAnalyzer/ExpectationAnalyzer.php
src/Rector/ClassMethod/MigrateAtToConsecutiveExpectationsRector.php
src/ValueObject/ExpectationMock.php
tests/Rector/ClassMethod/MigrateAtToConsecutiveExpectationsRector/Fixture/handle_property_fetch.php.inc

Handle mocks stored as properties in MigrateAtToConsecutiveExpectation

---

src/NodeAnalyzer/ExpectationAnalyzer.php
tests/Rector/ClassMethod/MigrateAtToConsecutiveExpectationsRector/Fixture/skip_missing_expects.php.inc

Closes #7.
Wasn't 100% sure of the best way to handle this - Happy to make changes to the fix based on feedback.

Support missing expects method in MigrateAtToConsecutiveExpectations

---

config/sets/phpunit80.php

Should DMS be included in the default PHPUnit 8 upgrade set?
Users can opt to use the DMS provided polyfill package by using the existing `phpunit80-dms.php` in addition to `phpunit80.php`.

Remove DMS from PHPUnit 8 set

---

src/Rector/MethodCall/AssertEqualsParameterToSpecificMethodsTypeRector.php
src/Rector/MethodCall/DelegateExceptionArgumentsRector.php

Based on https://github.com/rectorphp/rector-src/pull/812 as this direct call is deprecated.

[PostRector] Using NodesToAddCollector on rector rules

---

src/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector.php

The `getObjectType()` is deprecated at rector-src's AbstractRector
https://github.com/rectorphp/rector-src/blob/c6473c6a0b4ecaab710353e83f0c740e2e998d26/src/Rector/AbstractRector.php#L335-L338
This PR update to use NodeTypeResolver->getType()

[PHPUnit] Using NodeTypeResolver->getType() instead of deprecated getObjectType()

---

phpstan.neon
src/Rector/MethodCall/AssertIssetToSpecificMethodRector.php
src/ValueObject/ExpectationMockCollection.php
tests/Rector/MethodCall/AssertIssetToSpecificMethodRector/Fixture/skip_if_magic_method_isset_exists_in_parent.php.inc

Given the following code:
```php
// parent class not loaded
final class CustomIsset2 extends SomeAbstractClass {
}
final class SkipCustomIsset2 extends \PHPUnit\Framework\TestCase
{
public function test()
{
$foo = new CustomIsset2();
$this->assertTrue(isset($foo->bar));
}
}
```
It result:
```diff
-        $this->assertTrue(isset($foo->bar));
+        $this->assertObjectHasAttribute('bar', $foo);
```
which may be invalid as `SomeAbstractClass` not found by PHPStan, which may actually exists, but not loaded early. 
This PR handle it.

[PHPUnit] Skip AssertIssetToSpecificMethodRector when parent class not detected by PHPStan

---

src/Rector/Class_/ConstructClassMethodToSetUpTestCaseRector.php
tests/Rector/Class_/ConstructClassMethodToSetUpTestCaseRector/FixtureInnerClass/skip_inner_class.php.inc
tests/Rector/Class_/ConstructClassMethodToSetUpTestCaseRector/InnerClassTest.php
tests/Rector/Class_/ConstructClassMethodToSetUpTestCaseRector/config/inner_class_configured_rule.php

Fixes https://github.com/rectorphp/rector/issues/6893

Skip Inner class __construct on ConstructClassMethodToSetUpTestCaseRector

---

src/NodeAnalyzer/ExpectationAnalyzer.php
tests/Rector/ClassMethod/MigrateAtToConsecutiveExpectationsRector/Fixture/skip_dynamic_variable.php.inc
tests/Rector/ClassMethod/MigrateAtToConsecutiveExpectationsRector/Fixture/skip_other_class_types.php.inc

Ref rectorphp/rector#6976
Follow up to https://github.com/rectorphp/rector-phpunit/pull/41

Fix MigrateAtToConsecutiveExpectationsRector for other types

---

composer.json
easy-ci.php
src/Naming/TestClassNameResolver.php
src/Naming/TestClassNameResolverInterface.php
src/Rector/Class_/AddSeeTestAnnotationRector.php

PR for https://github.com/rectorphp/rector-phpunit/issues/51
I have tested this locally by applying a patch to the rector's vendor directory, and then in `rector.php`
```php
$services->set(
\Rector\PHPUnit\Naming\TestClassNameResolverInterface::class,
\Utils\Rector\Rector\PHPUnit\Naming\CustomTestClassNameResolver::class
);
```

[Feature] Add TestClassNameResolverInterface to allow custom implementations

---

src/NodeAnalyzer/AssertCallAnalyzer.php
tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Fixture/skip_expect_output.php.inc

Fixes https://github.com/rectorphp/rector/issues/7101

[PHPUnit] Skip expectOutput prefix on AddDoesNotPerformAssertionToNonAssertingTestRector

---

tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Fixture/skip_expect_output.php.inc

`expectOutputString()` should be `expectOutputRegex()` in 2nd example.

Typo Fix copy paste

---

src/NodeAnalyzer/MockedVariableAnalyzer.php
tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Fixture/skip_mock_expectations.php.inc
tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Source/CacheAdapter.php
tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Source/CacheInterface.php

Closes #107 Fixes https://github.com/rectorphp/rector/issues/7448
For use case:
```php
/** @var CacheInterface&MockObject */
private MockObject $cache;
```

[PHPUnit] Skip IntersectionType with MockObject on AddDoesNotPerformAssertionToNonAssertingTestRector

---

config/sets/annotations-to-attributes.php
src/Set/PHPUnitSetList.php
tests/AnnotationsToAttributes/AnnotationsToAttributesTest.php
tests/AnnotationsToAttributes/Fixture/small_fixture.php.inc
tests/AnnotationsToAttributes/config/annotationsToAttributes.php

PHPUnit will support [attributes](https://github.com/sebastianbergmann/phpunit/issues/4502) in version 10.  
It would be cool to have day 1 support.
ref issue: https://github.com/rectorphp/rector-phpunit/issues/69
This is work in progress because currently `AnnotationToAttribute`:
1. do not support syntax like: `@dataProvider  data`  or `@group api` (those are probably most common)
2. are not aware if the annotation is attached to method or class
Probably some new class like `PHPUnitAnnotationToAttribute` is needed.
@TomasVotruba Any feedback is welcome.

[WIP][Set] Annotation to attribute

---

composer.json
config/sets/annotations-to-attributes.php
docs/rector_rules_overview.md
src/Rector/Class_/AnnotationWithValueToAttributeRector.php
src/Rector/Class_/CoversAnnotationWithValueToAttributeRector.php
tests/Rector/Class_/CoversAnnotationWithValueToAttributeRector/CoversAnnotationWithValueToAttributeRectorTest.php
tests/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Fixture/covers_class.php.inc
tests/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Fixture/covers_function.php.inc
tests/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Source/ExistingClass.php
tests/Rector/Class_/CoversAnnotationWithValueToAttributeRector/config/configured_rule.php

* Ref https://github.com/rectorphp/rector-phpunit/issues/69
* Ref https://github.com/sebastianbergmann/phpunit/issues/4502
```diff
use PHPUnit\Framework\TestCase;
+use PHPUnit\Framework\Attributes\CoversClass;
+use PHPUnit\Framework\Attributes\CoversFunction;
-/**
- * @covers SomeClass
- */
+#[CoversClass(SomeClass::class)]
final class SomeTest extends TestCase
{
-    /**
-     * @covers ::someFunction
-     */
+    #[CoversFunction('someFunction')]
public function test()
{
}
}
```

[PHPUnit 10] Add CoversAnnotationWithValueToAttributeRector

---

config/sets/annotations-to-attributes.php
src/Rector/ClassMethod/DependsAnnotationWithValueToAttributeRector.php
tests/Rector/ClassMethod/DependsAnnotationWithValueToAttributeRector/DependsAnnotationWithValueToAttributeRectorTest.php
tests/Rector/ClassMethod/DependsAnnotationWithValueToAttributeRector/Fixture/fixture.php.inc
tests/Rector/ClassMethod/DependsAnnotationWithValueToAttributeRector/Fixture/skip_no_annotation.php.inc
tests/Rector/ClassMethod/DependsAnnotationWithValueToAttributeRector/Fixture/skip_not_test_class.php.inc
tests/Rector/ClassMethod/DependsAnnotationWithValueToAttributeRector/config/configured_rule.php

Add `DependsAnnotationWithValueToAttributeRector`, current functionality will only cover current class method, for external, it needs another PR iteration.

[PHPUnit] Add DependsAnnotationWithValueToAttributeRector

---

src/Rector/Class_/AnnotationWithValueToAttributeRector.php

Attributes only exists in php 8+, so `MinPhpVersionInterface` is needed for it.

[PHPUnit] Apply MinPhpVersionInterface on AnnotationWithValueToAttributeRector

---

src/Rector/ClassMethod/DependsAnnotationWithValueToAttributeRector.php
src/Rector/Class_/CoversAnnotationWithValueToAttributeRector.php

Attributes only exists in php 8+, so MinPhpVersionInterface is needed for it.

[PHPUnit] Apply MinPhpVersionInterface on CoversAnnotationWithValueToAttributeRector and DependsAnnotationWithValueToAttributeRector

---

src/NodeFinder/DataProviderClassMethodFinder.php

This PR, when merged, would unblock the ~failures~ failure described in #142.
Handling non-final classes that define data provider methods and not use them themself could be handled as a feature, I guess.

Ignore non existent data provider methods

---

composer.json
docs/rector_rules_overview.md
easy-ci.php

Per discussion on https://github.com/rectorphp/rector/issues/7752#issuecomment-1413397028

Remove check-markdown command from composer fix-cs and composer docs

---

src/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector.php
tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Fixture/skip_already_attributed_doesnot_perform_assertion.php.inc

When already in phpunit 10 with attribute `DoesNotPerformAssertions`, the addition `@doesNotPerformAssertions` is not needed.

[PhpUnit] Skip Already attributed DoesNotPerformAssertions on AddDoesNotPerformAssertionToNonAssertingTestRector

---

composer.json
ecs.php
phpstan.neon
rector.php
src/Rector/ClassLike/RemoveTestSuffixFromAbstractTestClassesRector.php
tests/Rector/ClassLike/RemoveTestSuffixFromAbstractTestClassesRector/Expected/ExtendsTestCase.php
tests/Rector/ClassLike/RemoveTestSuffixFromAbstractTestClassesRector/Fixture/extends_test.php.inc
tests/Rector/ClassLike/RemoveTestSuffixFromAbstractTestClassesRector/Fixture/replace_abstract_class_with_suffix_test.php.inc
tests/Rector/ClassLike/RemoveTestSuffixFromAbstractTestClassesRector/Fixture/skip_abstract_class_without_suffix.php.inc
tests/Rector/ClassLike/RemoveTestSuffixFromAbstractTestClassesRector/RemoveTestSuffixFromAbstractTestClassesRectorTest.php
tests/Rector/ClassLike/RemoveTestSuffixFromAbstractTestClassesRector/config/configured_rule.php

- [RemoveTestSuffixFromAbstractTestClassesRector] Add new rule (#132)
- Make use of new file asserts
Closes https://github.com/rectorphp/rector-phpunit/issues/132

Add RemoveTestSuffixFromAbstractTestClassesRector

---

src/Rector/ClassLike/RemoveTestSuffixFromAbstractTestClassesRector.php

https://github.com/rectorphp/rector/issues/7767
https://github.com/rectorphp/rector/issues/7767#issuecomment-1424577054

remove abstract *Test source file after renaming to *TestCase

---

src/NodeAnalyzer/AssertCallAnalyzer.php
src/NodeFinder/DataProviderClassMethodFinder.php
src/Rector/MethodCall/ExplicitPhpErrorApiRector.php

After update to phpstan 1.10.11, there is notice:
```
➜  rector-phpunit git:(main) composer phpstan
> vendor/bin/phpstan analyse --ansi --error-format symplify
Note: Using configuration file /Users/samsonasik/www/rector-phpunit/phpstan.neon.
198/198 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
src/NodeFinder/DataProviderClassMethodFinder.php:124
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- '#Method Rector\\PHPUnit\\NodeFinder\\DataProviderClassMethodFinder\:\:resolvePar …
```

Fix phpstan notice on update to phpstan 1.10.11

---

src/Rector/ClassMethod/CreateMockToAnonymousClassRector.php

@staabm this should fix https://github.com/rectorphp/rector-phpunit/issues/169

[BetterReflection 6.x] Fix assert($startLine > 0) on CreateMockToAnonymousClassRector

---

src/Rector/Class_/CoversAnnotationWithValueToAttributeRector.php
tests/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Fixture/covers_class.php.inc
tests/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Fixture/covers_method.php.inc

closes https://github.com/rectorphp/rector/issues/7873

Keep `#[CoversClass]` attribute on method, and don't move it to class scope

---

src/Rector/Class_/StaticDataProviderClassMethodRector.php
tests/Rector/Class_/StaticDataProviderClassMethodRector/Fixture/skip_containing_this.php.inc
tests/Rector/Class_/StaticDataProviderClassMethodRector/Source/SomeClassToMock.php

closes https://github.com/rectorphp/rector/issues/7872

StaticDataProviderClassMethodRector should only run if `$this` is not used in dataProvider

---

docs/rector_rules_overview.md
src/Rector/Class_/ProphecyPHPDocRector.php
tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Fixture/skip_prophecy_should.php.inc
tests/Rector/Class_/ProphecyPHPDocRector/Fixture/class_const.php.inc
tests/Rector/Class_/ProphecyPHPDocRector/Fixture/class_const_exist_phpdoc.php.inc
tests/Rector/Class_/ProphecyPHPDocRector/Fixture/short_classes.php.inc
tests/Rector/Class_/ProphecyPHPDocRector/Fixture/string_value.php.inc

Fix: Reduce visibility

---

src/Rector/Class_/PreferPHPUnitThisCallRector.php
tests/Rector/Class_/PreferPHPUnitThisCallRector/Fixture/replace_none_static_skip_static_function.php.inc

This should fix: https://github.com/rectorphp/rector-phpunit/pull/194#discussion_r1234849677
I removed:
```php
if (! $this->isObjectType($node->class, new ObjectType('PHPUnit\Framework\TestCase'))) {
return null;
}
```
Because we already check if we are in test case on line 73 `if (! $this->testsNodeAnalyzer->isInTestClass($node)) {` and i thought it was unnecessary to do this extra check.
And i got
``` 
src/Rector/Class_/PreferPHPUnitThisCallRector.php:72
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- '#Cognitive complexity for …
```

[PreferPHPUnitThisCallRector] Skip current and child funct fixes #8008

---

config/sets/phpunit100.php
docs/rector_rules_overview.md
src/Rector/Class_/ArrayArgumentToDataProviderRector.php
src/Rector/MethodCall/PropertyExistsWithoutAssertRector.php
tests/Rector/MethodCall/PropertyExistsWithoutAssertRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/PropertyExistsWithoutAssertRector/Fixture/fixture2.php.inc
tests/Rector/MethodCall/PropertyExistsWithoutAssertRector/Fixture/fixture3.php.inc
tests/Rector/MethodCall/PropertyExistsWithoutAssertRector/Fixture/fixture4.php.inc
tests/Rector/MethodCall/PropertyExistsWithoutAssertRector/PropertyExistsWithoutAssertRectorTest.php
tests/Rector/MethodCall/PropertyExistsWithoutAssertRector/config/configured_rule.php

Removes the now deprecated property/method exists PHPUnit assertions and
replaces them with plain PHP equivalents.

Add PropertyExistsWithoutAssertRector

---

config/sets/level/up-to-phpunit-91.php
config/sets/phpunit100.php
config/sets/phpunit91.php
src/Set/PHPUnitLevelSetList.php
src/Set/PHPUnitSetList.php

This address issue from https://github.com/rectorphp/rector-phpunit/pull/206
The sets should always target only the major version, as PHPUnit is quite a small package with well done BC compatibility. Splitting sets into minor version would create extreeme complexity. Let's make it simple instead :)

[DX] Merge 9.1 set to PHPUnit 10, to keep it simple and major-only as all other sets

---

src/Rector/MethodCall/AssertTrueFalseToSpecificMethodRector.php

instead of creating all objects and storing them in memory via the `__construct` method.

Refactor `AssertTrueFalseToSpecificMethodRector` to create new object when needed

---

rules/CodeQuality/Rector/MethodCall/AssertComparisonToSpecificMethodRector.php
rules/CodeQuality/Rector/MethodCall/AssertFalseStrposToContainsRector.php
rules/CodeQuality/Rector/MethodCall/AssertIssetToSpecificMethodRector.php
rules/CodeQuality/Rector/MethodCall/AssertPropertyExistsRector.php
rules/CodeQuality/Rector/MethodCall/AssertTrueFalseToSpecificMethodRector.php
rules/PHPUnit100/Rector/MethodCall/PropertyExistsWithoutAssertRector.php

Use native `array_merge()` instead, after all removed, we can remove the `appendArgs()` method from `AbstractRector`.

[DX] Remove appendArgs() usage on rector-phpunit rules

---

rules/PHPUnit90/Rector/MethodCall/ExplicitPhpErrorApiRector.php

The applied change return null already in line 98 under loop
https://github.com/rectorphp/rector-phpunit/blob/3b48901693f0d960790af65f73b36b36436badd0/rules/PHPUnit90/Rector/MethodCall/ExplicitPhpErrorApiRector.php#L95-L98

[PhpUnit90] Return null on no change on ExplicitPhpErrorApiRector

---

.github/workflows/code_analysis.yaml
.github/workflows/tests.yaml

Current github actions/checkout v3 got error:
```
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_4ecd32f5-c361-435e-b74b-7171ccb18414/3c125ce6-395a-4023-acd8-39fc47eba947.tar.gz. return code: 2.
```
Ref https://github.com/rectorphp/rector-src/actions/runs/6074243601/job/16477779233#step:1:35
It reported at:
- https://github.com/actions/checkout/issues/1448
This PR try to update to github actions/checkout v4.

Update github actions/checkout from v3 to v4

---

src/NodeAnalyzer/SetUpMethodDecorator.php

@Knallcharge this should fix https://github.com/rectorphp/rector/issues/8188
The `Identifier` must be rebuild for bring Node assign from `AstResolver`.

[NodeAnalyzer] Fix crash on set returnType on setUp() method on ConstructClassMethodToSetUpTestCaseRector

---

rules-tests/CodeQuality/Rector/Class_/AddSeeTestAnnotationRector/Fixture/some_test.php
rules-tests/CodeQuality/Rector/Class_/AddSeeTestAnnotationRector/Fixture/some_test.php.inc
rules/CodeQuality/Rector/Class_/AddSeeTestAnnotationRector.php

@TomasVotruba @staabm here based on https://github.com/rectorphp/rector-src/pull/4980#issuecomment-1713784117

 [CodeQualitiy] Use str_ends_with instead of isName(, '*Test') 

---

rules/AnnotationsToAttributes/Rector/ClassMethod/TestWithAnnotationToAttributeRector.php

Fix/259 Add php min version for TestWithAnnotationToAttributeRector

---

rector.php
rules/AnnotationsToAttributes/Rector/ClassMethod/DataProviderAnnotationToAttributeRector.php
rules/AnnotationsToAttributes/Rector/ClassMethod/DependsAnnotationWithValueToAttributeRector.php
rules/AnnotationsToAttributes/Rector/ClassMethod/TestWithAnnotationToAttributeRector.php
rules/AnnotationsToAttributes/Rector/Class_/AnnotationWithValueToAttributeRector.php
rules/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector.php
rules/AnnotationsToAttributes/Rector/Class_/TicketAnnotationToAttributeRector.php
rules/CodeQuality/Rector/ClassMethod/ReplaceTestAnnotationWithPrefixedFunctionRector.php
rules/CodeQuality/Rector/Class_/AddSeeTestAnnotationRector.php
rules/CodeQuality/Rector/Class_/YieldDataProviderRector.php
rules/CodeQuality/Rector/MethodCall/AssertRegExpRector.php
rules/CodeQuality/Rector/MethodCall/AssertSameTrueFalseToAssertTrueFalseRector.php
rules/PHPUnit100/Rector/Class_/AddProphecyTraitRector.php
rules/PHPUnit100/Rector/Class_/StaticDataProviderClassMethodRector.php
rules/PHPUnit60/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector.php
rules/PHPUnit60/Rector/ClassMethod/ExceptionAnnotationRector.php
rules/PHPUnit80/Rector/MethodCall/AssertEqualsParameterToSpecificMethodsTypeRector.php
rules/PHPUnit90/Rector/MethodCall/SpecificAssertContainsWithoutIdentityRector.php
src/Rector/StmtsAwareInterface/WithConsecutiveRector.php

Ref
- https://github.com/rectorphp/rector-src/pull/5051
- https://github.com/rectorphp/rector-src/pull/5052
- https://github.com/rectorphp/rector-src/pull/5053

Move betterNodeFinder,valueResolver,phpDocInfoFactory dependencies from AbstractRector into rules

---

rules-tests/Transform/Rector/AssertEqualsOrAssertSameFloatParameterToSpecificMethodsTypeRector/Fixture/fixture.php.inc
src/Transform/AssertEqualsOrAssertSameFloatParameterToSpecificMethodsTypeRector.php

In php 7.2 was introduced [PHP_FLOAT_EPSILON](https://www.php.net/manual/en/reserved.constants.php#constant.php-float-epsilon) and I could use this as a small representation for decimal delta.
https://github.com/sebastianbergmann/phpunit/pull/4874
https://github.com/sebastianbergmann/phpunit/issues/3159#issuecomment-1022240982.
and I tested with diffident values and it worked as expected.

Replace decimal delta value for PHP_FLOAT_EPSILON

---

docs/rector_rules_overview.md
rules-tests/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Fixture/covers_class_default.php.inc
rules-tests/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Fixture/covers_function.php.inc
rules-tests/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Fixture/covers_function_method.php.inc
rules-tests/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Fixture/covers_method.php.inc
rules-tests/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Source/ExistingClass.php
rules-tests/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Source/HelperClass.php
rules/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector.php
tests/Issues/DoubleAnnotation/Fixture/some_test.php.inc

Changed refactors done in `CoversAnnotationWithValueToAttributeRector.php` so that
- [CoversClass](https://github.com/sebastianbergmann/phpunit/blob/main/src/Framework/Attributes/CoversClass.php), [CoversFunction](https://github.com/sebastianbergmann/phpunit/blob/main/src/Framework/Attributes/CoversFunction.php)  attributes are added on class level (in accordance with their respective `#[Attribute ... ]` values). 
- `@covers` annotations are removed from method level
- Duplicate covers attributes are unified
- `@coversDefault` is converted to a `CoversClass` attribute

PHPUnit10 Attributes

---

config/sets/phpunit100.php

Feature/267 Add rule to replace setMethods to onlyMethods

---

config/sets/phpunit100.php

On issue https://github.com/sebastianbergmann/phpunit/issues/5062 was deprecated few methods.
then I am applying the replacement for methods that has other method to substitute.
you can check here in this file: https://github.com/sebastianbergmann/phpunit/blob/9.6/src/Framework/TestCase.php

Replace deprecated methods from phpunit issue 5062

---

config/sets/phpunit-code-quality.php
docs/rector_rules_overview.md
rules-tests/CodeQuality/Rector/MethodCall/AssertEqualsOrAssertSameFloatParameterToSpecificMethodsTypeRector/AssertEqualsOrAssertSameFloatParameterToSpecificMethodsTypeRectorTest.php
rules-tests/CodeQuality/Rector/MethodCall/AssertEqualsOrAssertSameFloatParameterToSpecificMethodsTypeRector/Fixture/fixture.php.inc
rules-tests/CodeQuality/Rector/MethodCall/AssertEqualsOrAssertSameFloatParameterToSpecificMethodsTypeRector/config/configured_rule.php
rules/CodeQuality/Rector/MethodCall/AssertEqualsOrAssertSameFloatParameterToSpecificMethodsTypeRector.php

@TomasVotruba I guess we should also move this rule for CodeQuality, WDYT?

Move AssertEqualsOrAssertSameFloatParameterToSpecificMethodsTypeRector to CodeQuality

---

config/sets/phpunit-code-quality.php
docs/rector_rules_overview.md
rules-tests/CodeQuality/Rector/ClassMethod/DataProviderArrayItemsNewLinedRector/DataProviderArrayItemsNewLinedRectorTest.php
rules-tests/CodeQuality/Rector/ClassMethod/DataProviderArrayItemsNewLinedRector/Fixture/fixture.php.inc
rules-tests/CodeQuality/Rector/ClassMethod/DataProviderArrayItemsNewLinedRector/config/configured_rule.php
rules/CodeQuality/Rector/ClassMethod/DataProviderArrayItemsNewLinedRector.php

- Move `DataProviderArrayItemsNewLinedRector` from rector repository.
- Add test for DataProviderArrayItemsNewLinedRector
- Add group rule set for coding style
after this PR pass I will remove the rule from rector repository.
Issue #287

Feature/287 Move DataProviderArrayItemsNewLinedRector to rector-phpunit repository

---

rules/AnnotationsToAttributes/Rector/ClassMethod/DataProviderAnnotationToAttributeRector.php
src/Rector/StmtsAwareInterface/WithConsecutiveRector.php

`DataProviderAnnotationToAttributeRector.php` and `WithConsecutiveRector.php` just work for phpunit10, But as there isn't the possibility to strict rules by `phpunit version`, then I am changing for the minimum version supported for phpunit10 (php 8.1)
Close #272

Fix/272 Strict phpunit10 feature for php 81

---

rules-tests/CodeQuality/Rector/ClassMethod/DataProviderArrayItemsNewLinedRector/Fixture/skip_comment_inline.php.inc
rules/CodeQuality/Rector/ClassMethod/DataProviderArrayItemsNewLinedRector.php

array with inline comment should be skipped instead of re-printed, it currently produce invalid change:
```diff
public function provideData(): array
{
return [
-            ['content123', 11], // a comment inline
+            ['content123', 11],
```

[CodeQuality] Skip inline comment on DataProviderArrayItemsNewLinedRector

---

config/sets/phpunit-code-quality.php
config/sets/phpunit100.php

Deprecated in PPHPUnit 8.3 see: https://github.com/sebastianbergmann/phpunit/commit/d618fa3fda437421264dcfa1413a474f306f79c4
Fixes #292

setMethods call has been removed in PHPUnit 10

---

config/sets/phpunit100.php
docs/rector_rules_overview.md
rules-tests/PHPUnit100/Rector/MethodCall/RemoveSetMethodsMethodCallRector/Fixture/keep_unrelated_set_methods.php.inc
rules-tests/PHPUnit100/Rector/MethodCall/RemoveSetMethodsMethodCallRector/Fixture/some_class.php.inc
rules-tests/PHPUnit100/Rector/MethodCall/RemoveSetMethodsMethodCallRector/RemoveSetMethodsMethodCallRectorTest.php
rules-tests/PHPUnit100/Rector/MethodCall/RemoveSetMethodsMethodCallRector/config/configured_rule.php
rules/PHPUnit100/Rector/MethodCall/RemoveSetMethodsMethodCallRector.php

Move RemoveSetMethodsMethodCallRector and its tests to correct namespace.
As per: https://github.com/rectorphp/rector-phpunit/pull/293#issuecomment-1806286903

RemoveSetMethodsMethodCallRector: move tests and classes to new location

---

rules-tests/PHPUnit60/Rector/MethodCall/DelegateExceptionArgumentsRector/Fixture/before_test_stmt.php.inc
rules-tests/PHPUnit60/Rector/MethodCall/DelegateExceptionArgumentsRector/Fixture/before_test_stmt_with_code.php.inc
rules/PHPUnit60/Rector/MethodCall/DelegateExceptionArgumentsRector.php

It currently add `expectExceptionMessage()` after test part, it should be immediate after `expectException()`
```diff
There was 1 failure:
1) Rector\PHPUnit\Tests\PHPUnit60\Rector\MethodCall\DelegateExceptionArgumentsRector\DelegateExceptionArgumentsRectorTest::test with data set #1
Failed on fixture file "before_test_stmt.php.inc"
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
public function test()
{
$this->expectException('SecondException');
+        $this->execute();
$this->expectExceptionMessage($message);
-        $this->execute();
}
private function execute()
```
Ref https://getrector.com/demo/d1033af1-10a9-4406-ab5e-775bef099e4f

[PhpUnit60] Handle before stmt execute to test on DelegateExceptionArgumentsRector

---

tests/Issues/PHPUnit10DataProvider/Fixture/some_test.php.inc
tests/Issues/PHPUnit10DataProvider/PHPUnit10DataProviderTest.php
tests/Issues/PHPUnit10DataProvider/config/configured_rule.php

Fixes https://github.com/rectorphp/rector/issues/8360

[PHPUnit 10] Handle DataProvider attribute not included on use PHPUnitSetList::PHPUNIT_100

---

config/sets/phpunit100.php
docs/rector_rules_overview.md
rules-tests/PHPUnit100/Rector/Class_/PublicDataProviderClassMethodRector/Fixture/cover_no_bracket_name.php.inc
rules-tests/PHPUnit100/Rector/Class_/PublicDataProviderClassMethodRector/Fixture/handle_abstract_data_provider.php.inc
rules-tests/PHPUnit100/Rector/Class_/PublicDataProviderClassMethodRector/Fixture/multiple_data_providers.php.inc
rules-tests/PHPUnit100/Rector/Class_/PublicDataProviderClassMethodRector/Fixture/respect_parent_abstract_class.php.inc
rules-tests/PHPUnit100/Rector/Class_/PublicDataProviderClassMethodRector/Fixture/respect_parent_data_provider.php.inc
rules-tests/PHPUnit100/Rector/Class_/PublicDataProviderClassMethodRector/Fixture/skip_already_public.php.inc
rules-tests/PHPUnit100/Rector/Class_/PublicDataProviderClassMethodRector/Fixture/some_class.php.inc
rules-tests/PHPUnit100/Rector/Class_/PublicDataProviderClassMethodRector/PublicDataProviderClassMethodRectorTest.php
rules-tests/PHPUnit100/Rector/Class_/PublicDataProviderClassMethodRector/Source/AbstractClassWithDataProvider.php
rules-tests/PHPUnit100/Rector/Class_/PublicDataProviderClassMethodRector/Source/AnotherAbstractClass.php
rules-tests/PHPUnit100/Rector/Class_/PublicDataProviderClassMethodRector/Source/SomeClassToMock.php
rules-tests/PHPUnit100/Rector/Class_/PublicDataProviderClassMethodRector/config/configured_rule.php
rules/PHPUnit100/Rector/Class_/PublicDataProviderClassMethodRector.php

* Adds a new rule for making data provider methods public.
* Adds a new set of tests for the rule.
* Updates docs
* Adds the rule to the PHPUnit100 config.
PHPUnit 10 expects data providers to be both Public and Static whereas before both were not a requirement. There was already a rule for static data providers but protected/private scenario hasn't been covered. For ease of use I've created a new rule rather than changing the static rule to cover both scenarios.

[PHPUnit100] Adds the PublicDataProviderClassMethodRector rule

---

config/sets/annotations-to-attributes.php

As described in https://github.com/sebastianbergmann/phpunit/issues/5235 and https://github.com/sebastianbergmann/phpunit/issues/5513 the `CodeCoverageIgnore` attribute was a mistake and is now deprecated, therefore Rector should not try to replace annotation with the attribute.
Fixes #303

Remove `codeCoverageIgnore` to annotation to attribute conversion

---

docs/rector_rules_overview.md
src/Rector/StmtsAwareInterface/WithConsecutiveRector.php
tests/Rector/StmtsAwareInterface/WithConsecutiveRector/Fixture/some_class_static_invocation.php.inc

PR is intended to give ability to refactor withConsecutive when static invocation checker applied
According to PHPUnit [there is no difference between static and non-static assertions](https://docs.phpunit.de/en/10.5/assertions.html#static-vs-non-static-usage-of-assertion-methods) but it sounds like invocation count checkers have the same ability and there is no difference between self::exactly and $this->exactly

WithConsecutiveRector was applied only to dynamic invocations count

---

rules-tests/CodeQuality/Rector/MethodCall/AssertEmptyNullableObjectToAssertInstanceofRector/Fixture/skip_no_arg.php.inc
rules/CodeQuality/Rector/MethodCall/AssertEmptyNullableObjectToAssertInstanceofRector.php

Fixes https://github.com/rectorphp/rector/issues/8527 for whatever reason to not have arg on the first place, eg: different object caller.

[PHPUnit][CodeQuality] Skip no arg on AssertEmptyNullableObjectToAssertInstanceofRector

---

.github/workflows/code_analysis.yaml

This is a follow up for https://github.com/rectorphp/rector-phpunit/pull/320 and related to https://github.com/rectorphp/rector-phpunit/pull/319#issuecomment-2035137884
Instead of duplicating command line on `code_analysis.yaml` action file, we can just reuse `composer class-leak` from `composer.json`.
Each time `composer class-leak` is updated, it will be automatically used on GH Action, so no need to update duplicated command twice.
Without it, we will have an issue when we start addign `--skip-type` for `vendor/bin/class-leak` in `code_analysis.yaml`. The same `--skip-type` would be added to 2 places without this PR.

Reuse composer's script for `class-leak` rather than duplicate command line on GH action

---

composer.json

This is a follow up for https://github.com/rectorphp/rector-phpunit/pull/320 and should be merged after it.
Add `complete-check` composer script same as it's done in `rectorphp/rector-src`.
Example taken from:
https://github.com/rectorphp/rector-src/blob/fc250dd8da281cb79f5657d2f5d6c6c0053e54d1/composer.json#L106-L111

 Add `complete-check` composer script same as it's done in `rectorphp/rector-src`.

---

rules-tests/CodeQuality/Rector/Class_/AddCoversClassAttributeRector/Fixture/adds_covers_class_testcase.php.inc
rules/CodeQuality/Rector/Class_/AddCoversClassAttributeRector.php

In some projects (e.h. PHPUnit itself) testcase-names are ending in `TestCase` not just `Test`
running the new rector on phpunit itself yields a few false positives, e.g.
```diff
55) tests/unit/Framework/MockObject/TestDoubleTestCase.php:21
---------- begin diff ----------
@@ @@
use PHPUnit\TestFixture\MockObject\InterfaceWithReturnTypeDeclaration;
use stdClass;
+#[\PHPUnit\Framework\Attributes\CoversClass(\PHPUnit\Framework\MockObject\TestDoubleTestCase::class)]
abstract class TestDoubleTestCase extends TestCase
{
final public function testMethodReturnsNullWhenReturnValueIsNullableAndNoReturnValueIsConfigured(): void
----------- end diff -----------
Applied rules:
* AddCoversClassAttributeRector
56) tests/unit/Metadata/Parser/AnnotationParserTestCase.php:41
---------- begin diff …
```

AddCoversClassAttributeRector: Support *TestCase suffix

---

rules-tests/CodeQuality/Rector/Class_/AddCoversClassAttributeRector/Fixture/skips_interfaces.php.inc
rules-tests/CodeQuality/Rector/Class_/AddCoversClassAttributeRector/Fixture/skips_traits.php.inc
rules/CodeQuality/Rector/Class_/AddCoversClassAttributeRector.php

`CoversClass` annotation should not be used with interfaces or traits
see 
- https://github.com/sebastianbergmann/phpunit/blob/53eebaa2a68b737b309ca2d4deb8fe961eb71200/src/Metadata/Api/CodeCoverage.php#L277-L284
- https://github.com/sebastianbergmann/phpunit/blob/53eebaa2a68b737b309ca2d4deb8fe961eb71200/src/Metadata/Api/CodeCoverage.php#L286-L293

AddCoversClassAttributeRector: skip interfaces & traits

---

rules-tests/CodeQuality/Rector/Class_/AddCoversClassAttributeRector/Fixture/skips_abstract_class.php.inc
rules/CodeQuality/Rector/Class_/AddCoversClassAttributeRector.php

quoting sebastian bergmann:
> This has no effect as AttributeParserTestCase is an abstract class and only metadata on concrete test classes is used.
see https://github.com/sebastianbergmann/phpunit/pull/5814#discussion_r1568275673

AddCoversClassAttributeRector: skip abstract classes

---

rules-tests/CodeQuality/Rector/MethodCall/AssertInstanceOfComparisonRector/Fixture/fixture.php.inc
rules/CodeQuality/Rector/MethodCall/AssertInstanceOfComparisonRector.php

Rule `InstanceOfComparisonRector` doesn't work when we pass a variable as the second argument to operator `instanceof`. This PR fixes it.

Fix InstanceOfComparisonRector for variables

---

src/Rector/Class_/PreferPHPUnitSelfCallRector.php
tests/Rector/Class_/PreferPHPUnitSelfCallRector/Fixture/skip_non_static_assert.php.inc

In my project, I have self-defined `assert` methods that are not static because they need to access some instance variables. But the `PreferPHPUnitSelfCallRector` rule converts all method calls to static calls because the names match.
I created a patch that additionally checks if the `assert` method can be called statically.

Check if an assert method is static before calling it with self

---

docs/rector_rules_overview.md
rules-tests/PHPUnit110/Rector/Class_/NamedArgumentForDataProviderRector/Fixture/array.php.inc
rules-tests/PHPUnit110/Rector/Class_/NamedArgumentForDataProviderRector/Fixture/handle_missing.php.inc
rules-tests/PHPUnit110/Rector/Class_/NamedArgumentForDataProviderRector/Fixture/mixed_keys.php.inc
rules-tests/PHPUnit110/Rector/Class_/NamedArgumentForDataProviderRector/Fixture/skip_changed_order.php.inc
rules-tests/PHPUnit110/Rector/Class_/NamedArgumentForDataProviderRector/Fixture/skip_non_tests.php.inc
rules-tests/PHPUnit110/Rector/Class_/NamedArgumentForDataProviderRector/Fixture/skip_numeric.php.inc
rules-tests/PHPUnit110/Rector/Class_/NamedArgumentForDataProviderRector/Fixture/unpack.php.inc
rules-tests/PHPUnit110/Rector/Class_/NamedArgumentForDataProviderRector/Fixture/yield.php.inc
rules-tests/PHPUnit110/Rector/Class_/NamedArgumentForDataProviderRector/NamedArgumentForDataProviderRectorTest.php
rules-tests/PHPUnit110/Rector/Class_/NamedArgumentForDataProviderRector/config/configured_rule.php
rules/PHPUnit110/Rector/Class_/NamedArgumentForDataProviderRector.php

Create a rector rule that will rename the array keys from the PHPUnit Dataprovider to the argument name of the called test method to be prepared for the usage of named arguments in PHPUnit 11. This was already deprecated in PHPUnit 10.5
I think this is a risky rule because you could use the same dataProvider for multiple tests and the name of the arguments could be differ between the methods. (That's the point why i didn't added it to a new PHPUnit110 list)
Maybe it make sense to add an configurable option to remove the array key names completly to not use the named argument feature at all?

Create a rector rule that will rename the array keys from the PHPUnit Dataprovider

---

rules-tests/CodeQuality/Rector/MethodCall/AssertCompareToSpecificMethodRector/Fixture/skip_get_type.php.inc
rules/CodeQuality/Rector/MethodCall/AssertCompareToSpecificMethodRector.php

While upgrade is valid for one PHPUnit version, it will be deprecated next one.
The best way to go is to skip `gettype` check.
Closes https://github.com/rectorphp/rector/issues/8593

Fix AssertCompareToSpecificMethodRector to skip gettype checks, as will be deprecated in next PHPUnit version

---

config/sets/phpunit100.php

Ref https://github.com/rectorphp/rector-phpunit/pull/338#pullrequestreview-2133908428
**Before**
```
There was 1 error:
1) CodeIgniter\Config\BaseConfigTest::testEnvironmentOverrides
Error: Call to undefined method CodeIgniter\Config\BaseConfigTest::assertObjectHasNotProperty()
/Users/samsonasik/www/CodeIgniter4/tests/system/Config/BaseConfigTest.php:134
```
**After**
```
➜  CodeIgniter4 git:(develop) ✗ vendor/bin/phpunit tests/system/Config/BaseConfigTest.php
PHPUnit 10.5.24 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.3.4 with PCOV 1.0.11
Configuration: /Users/samsonasik/www/CodeIgniter4/phpunit.xml.dist
..................                                           18 / 18 (100%)
Time: 00:00.317, Memory: 14.00 MB
OK (18 tests, 48 assertions)
Generating code coverage …
```

[PHPUnit 10] Fix typo assertObjectHasNotProperty -> assertObjectNotHasProperty

---

rules/PHPUnit110/Rector/Class_/NamedArgumentForDataProviderRector.php

Fixes https://github.com/rectorphp/rector-phpunit/issues/344

Fix prefixed scoped DataProvider class on NamedArgumentForDataProviderRector

---

config/sets/phpunit110.php

Closes https://github.com/rectorphp/rector-phpunit/issues/346

Remove NamedArgumentForDataProviderRector from the PHPUnit 11 set as optional upgrade path

---

rules-tests/PHPUnit110/Rector/Class_/NamedArgumentForDataProviderRector/Fixture/multiple_dataprovider.php.inc
rules/PHPUnit110/Rector/Class_/NamedArgumentForDataProviderRector.php

Add support for multiple dataProviders for a single test method

---

rules-tests/PHPUnit100/Rector/MethodCall/AssertIssetToAssertObjectHasPropertyRector/Fixture/some_isset_to_property.php.inc
rules/PHPUnit100/Rector/MethodCall/AssertIssetToAssertObjectHasPropertyRector.php

AssertIssetToAssertObjectHasPropertyRector rule should change assertion to "assertObjectHasProperty". 
Function assertObjectHasAttribute doesn't exist in PHPUnit 10.5

[PHPUnit100] Fix typo in AssertIssetToAssertObjectHasPropertyRector

---

config/sets/phpunit-code-quality.php
docs/rector_rules_overview.md
rules-tests/CodeQuality/Rector/MethodCall/AssertCompareOnCountableWithMethodToAssertCountRector/AssertCompareOnCountableWithMethodToAssertCountRectorTest.php
rules-tests/CodeQuality/Rector/MethodCall/AssertCompareOnCountableWithMethodToAssertCountRector/Fixture/count.php.inc
rules-tests/CodeQuality/Rector/MethodCall/AssertCompareOnCountableWithMethodToAssertCountRector/Fixture/skip_on_non_test_class.php.inc
rules-tests/CodeQuality/Rector/MethodCall/AssertCompareOnCountableWithMethodToAssertCountRector/Source/Collection.php
rules-tests/CodeQuality/Rector/MethodCall/AssertCompareOnCountableWithMethodToAssertCountRector/config/configured_rule.php
rules/CodeQuality/Rector/MethodCall/AssertCompareOnCountableWithMethodToAssertCountRector.php

- Adds the new rule `AssertCompareOnCountableWithMethodToAssertCountRector`
- Adds a test
- Updates the docs
Based on this [PHPStan PHPUnit rule](https://github.com/phpstan/phpstan-phpunit/blob/1.4.x/src/Rules/PHPUnit/AssertRuleHelper.php) it will convert comparison on Countable objects with the count method to use the `assertCount` method instead.
Works with method and static method calls.
```diff
-$this->assertSame(1, $countable->count());
+$this->assertCount(1, $countable);
```

[CodeQuality] Assert compare on countable

---

rules/CodeQuality/Rector/Class_/PreferPHPUnitSelfCallRector.php
rules/CodeQuality/Rector/Class_/PreferPHPUnitThisCallRector.php
rules/CodeQuality/Rector/MethodCall/AssertCompareOnCountableWithMethodToAssertCountRector.php
rules/CodeQuality/Rector/MethodCall/AssertEqualsOrAssertSameFloatParameterToSpecificMethodsTypeRector.php
rules/CodeQuality/Rector/MethodCall/NarrowIdenticalWithConsecutiveRector.php
rules/CodeQuality/Rector/MethodCall/SingleWithConsecutiveToWithRector.php
rules/PHPUnit100/Rector/StmtsAwareInterface/WithConsecutiveRector.php

to avoid assert error on first class callable.

Ensure check isFirstClassCallable() before getArgs() call on CallLike

---

rules-tests/CodeQuality/Rector/MethodCall/SingleWithConsecutiveToWithRector/Fixture/simplify_equal_to.php.inc
rules-tests/CodeQuality/Rector/MethodCall/SingleWithConsecutiveToWithRector/Fixture/with_assert_inside.php.inc
rules/CodeQuality/Rector/MethodCall/NarrowSingleWillReturnCallbackRector.php
rules/CodeQuality/Rector/MethodCall/SingleWithConsecutiveToWithRector.php

- **add fialing fixture**
- **remove equalsTo()**

tv with consecutive callable single 4

---

rules-tests/AnnotationsToAttributes/Rector/Class_/AnnotationWithValueToAttributeRector/Fixture/skip_not_in_test.php.inc
rules-tests/AnnotationsToAttributes/Rector/Class_/AnnotationWithValueToAttributeRector/Fixture/uses_in_test.php.inc
rules-tests/AnnotationsToAttributes/Rector/Class_/AnnotationWithValueToAttributeRector/config/configured_rule.php
rules/AnnotationsToAttributes/Rector/Class_/AnnotationWithValueToAttributeRector.php

Like other rules, the `AnnotationWithValueToAttributeRector` should verify in test class as well.

[AnnotationsToAttribute] Skip not in test on AnnotationWithValueToAttributeRector

---

rules-tests/CodeQuality/Rector/ClassMethod/ReplaceTestFunctionPrefixWithAttributeRector/Fixture/fixture_camelCase.php.inc
rules-tests/CodeQuality/Rector/ClassMethod/ReplaceTestFunctionPrefixWithAttributeRector/Fixture/fixture_just_test_name.php.inc
rules-tests/CodeQuality/Rector/ClassMethod/ReplaceTestFunctionPrefixWithAttributeRector/Fixture/fixture_snake_case.php.inc
rules-tests/CodeQuality/Rector/ClassMethod/ReplaceTestFunctionPrefixWithAttributeRector/ReplaceTestFunctionPrefixWithAttributeRectorTest.php
rules-tests/CodeQuality/Rector/ClassMethod/ReplaceTestFunctionPrefixWithAttributeRector/config/configured_rule.php
rules/CodeQuality/Rector/ClassMethod/ReplaceTestFunctionPrefixWithAttributeRector.php

We have a project with lots of phpunit tests that were defined using just the `test` prefix on the function name. We'd like to move these to using the `#[Test]` attribute.
Since we probably aren't the only people with this setup we thought we'd contribute it back :)

Add ReplaceTestFunctionPrefixWithAttributeRector

---

composer.json
config/sets/phpunit-code-quality.php
rules-tests/CodeQuality/Rector/Class_/NarrowUnusedSetUpDefinedPropertyRector/Fixture/defined_only_in_setup.php.inc
rules-tests/CodeQuality/Rector/Class_/NarrowUnusedSetUpDefinedPropertyRector/Fixture/skip_non_mocks.php.inc
rules-tests/CodeQuality/Rector/Class_/NarrowUnusedSetUpDefinedPropertyRector/NarrowUnusedSetUpDefinedPropertyRectorTest.php
rules-tests/CodeQuality/Rector/Class_/NarrowUnusedSetUpDefinedPropertyRector/Source/SomeType.php
rules-tests/CodeQuality/Rector/Class_/NarrowUnusedSetUpDefinedPropertyRector/config/configured_rule.php
rules/CodeQuality/Rector/Class_/NarrowUnusedSetUpDefinedPropertyRector.php

- **misc**
- **[code-quality] Add NarrowUnusedSetUpDefinedPropertyRector**

[code-quality] Add NarrowUnusedSetUpDefinedPropertyRector

---

rules-tests/CodeQuality/Rector/Class_/NarrowUnusedSetUpDefinedPropertyRector/Fixture/non_private_on_final.php.inc
rules-tests/CodeQuality/Rector/Class_/NarrowUnusedSetUpDefinedPropertyRector/Fixture/skip_non_private_on_non_final.php.inc
rules/CodeQuality/Rector/Class_/NarrowUnusedSetUpDefinedPropertyRector.php

when class is not final, and property is non-private, it can be used by child class.

[CodeQuality] Skip non private on non final class on NarrowUnusedSetUpDefinedPropertyRector

---

rules-tests/CodeQuality/Rector/ClassMethod/EntityDocumentCreateMockToDirectNewRector/EntityDocumentCreateMockToDirectNewRectorTest.php
rules-tests/CodeQuality/Rector/ClassMethod/EntityDocumentCreateMockToDirectNewRector/Fixture/skip_no_property.php.inc
rules-tests/CodeQuality/Rector/ClassMethod/EntityDocumentCreateMockToDirectNewRector/Fixture/some_file.php.inc
rules-tests/CodeQuality/Rector/ClassMethod/EntityDocumentCreateMockToDirectNewRector/Source/Table.php
rules-tests/CodeQuality/Rector/ClassMethod/EntityDocumentCreateMockToDirectNewRector/config/configured_rule.php
rules/CodeQuality/NodeAnalyser/DoctrineEntityDocumentAnalyser.php
rules/CodeQuality/Rector/ClassMethod/EntityDocumentCreateMockToDirectNewRector.php

Instead of weak mocking setup, use object directly with type control and IDE support :tada: 
```diff
-$articleMock = $this->createMock(Article::class);
-$articleMock->method('getName')->willReturn('How stand up against mocking');
+$article = new Article();
+$article->setName('How stand up against mocking');
```
This rule is applied on Doctrine ORM + ODM entitites only, to have migration under control.

[CodeQuality] Add CreateMockToDirectNewRector

---

rules-tests/CodeQuality/Rector/Class_/YieldDataProviderRector/Fixture/use_data_provider_with_phpdoc.php.inc
rules/CodeQuality/Rector/Class_/YieldDataProviderRector.php

Closes https://github.com/rectorphp/rector-phpunit/pull/414

[PHPUnit] Change @return array<> to @return Iterator<> on YieldDataProviderRector

---

rules-tests/CodeQuality/Rector/Class_/YieldDataProviderRector/Fixture/use_data_provider_with_phpdoc.php.inc
rules/CodeQuality/Rector/Class_/YieldDataProviderRector.php

followtup to https://github.com/rectorphp/rector-phpunit/pull/416

[PHPUnit] Support list in YieldDataProviderRector

---

rules-tests/AnnotationsToAttributes/Rector/ClassMethod/TestWithAnnotationToAttributeRector/Fixture/with_numeric_string.php.inc

Fixture for patch on rector-src
- https://github.com/rectorphp/rector-src/pull/6608
for issue:
- https://github.com/rectorphp/rector/issues/8941

Add fixture for numeric string to keep as is on TestWithAnnotationToAttributeRector

---

rules-tests/CodeQuality/Rector/MethodCall/AssertEqualsToSameRector/Fixture/dynamic_bool.php.inc
rules/CodeQuality/Rector/MethodCall/AssertEqualsToSameRector.php

Fixes https://github.com/rectorphp/rector/issues/8945

[CodeQuality] Allow dynamic bool on AssertEqualsToSameRector

---

rules-tests/CodeQuality/Rector/MethodCall/AssertCompareOnCountableWithMethodToAssertCountRector/Fixture/count.php.inc
rules-tests/CodeQuality/Rector/MethodCall/AssertCompareOnCountableWithMethodToAssertCountRector/Fixture/direct_count_call.php.inc
rules-tests/CodeQuality/Rector/MethodCall/AssertCompareOnCountableWithMethodToAssertCountRector/Fixture/other_count_call.php.inc
rules/CodeQuality/Rector/MethodCall/AssertCompareOnCountableWithMethodToAssertCountRector.php

Previously
- It supported only assertEquals/assertSame
- It supported only count function
Now
- It also supports assertNotEquals/assertNotSame
- It also supports sizeof and iterator_count functions

Improve AssertCompareOnCountableWithMethodToAssertCountRector

---

rules-tests/CodeQuality/Rector/MethodCall/AssertInstanceOfComparisonRector/Fixture/get_class.php.inc
rules-tests/CodeQuality/Rector/MethodCall/AssertInstanceOfComparisonRector/Fixture/skip_first_param.inc
rules/CodeQuality/Rector/MethodCall/AssertInstanceOfComparisonRector.php

With the two recent PRs, 
AssertCompareToSpecificMethodRector is now fully covered by both
- AssertInstanceOfComparisonRector
- AssertCompareOnCountableWithMethodToAssertCountRector
Do we want to
- Deprecate AssertCompareToSpecificMethodRector in another PR ?
- At least remove AssertCompareToSpecificMethodRector from the CodeQuality set ? (Since it won't fix anything not covered by others rules)
@TomasVotruba

Improve AssertInstanceOfComparisonRector

---

rules-tests/CodeQuality/Rector/MethodCall/AssertEqualsToSameRector/Fixture/skip_loose_compare.php.inc
rules-tests/CodeQuality/Rector/MethodCall/AssertEqualsToSameRector/Fixture/skip_loose_compare2.php.inc
rules-tests/CodeQuality/Rector/MethodCall/AssertEqualsToSameRector/Fixture/skip_mixed_array_dim_fetch.php.inc
rules/CodeQuality/Rector/MethodCall/AssertEqualsToSameRector.php

The following should be skipped:
```php
$this->assertEquals(1.0, 1);
```
as cause error on assertSame().

[CodeQuality] Skip loose compare float vs integer on AssertEqualsToSameRector

---

rules-tests/CodeQuality/Rector/MethodCall/AssertEqualsToSameRector/Fixture/assert_same_constant_array.php.inc
rules-tests/CodeQuality/Rector/MethodCall/AssertEqualsToSameRector/Fixture/class_constant.php.inc
rules-tests/CodeQuality/Rector/MethodCall/AssertEqualsToSameRector/Fixture/php80_enum.php.inc
rules-tests/CodeQuality/Rector/MethodCall/AssertEqualsToSameRector/Fixture/skip_compare_mixed.php.inc
rules/CodeQuality/Rector/MethodCall/AssertEqualsToSameRector.php

compare to mixed is never guessable the type, can be anything, so this PR skip it.

[CodeQuality] Skip compare to mixed on AssertEqualsToSameRector

---

tests/AnnotationsToAttributes/Fixture/inline_docblock_tag.php.inc

Where an inline docblock is used in another tag, all subsequent tags are removed.
https://github.com/rectorphp/rector/issues/8977
I've tried to keep this as small as possible but have deliberately incldued:
* a text node
* a tag before the tag containing the inline tag
* a tag after the tag containing the inline tag
* the tag we want to convert to attribute

Added testcase to demonstrate rector#8977

---

rules-tests/PHPUnit100/Rector/MethodCall/PropertyExistsWithoutAssertRector/Fixture/fixture_static.php.inc
rules-tests/PHPUnit100/Rector/MethodCall/PropertyExistsWithoutAssertRector/PropertyExistsWithoutAssertRectorTest.php
rules-tests/PHPUnit100/Rector/MethodCall/PropertyExistsWithoutAssertRector/config/configured_rule.php
rules/PHPUnit100/Rector/MethodCall/PropertyExistsWithoutAssertRector.php

Replace deleted PHPUnit methods: 
assertClassHasStaticAttribute
classHasStaticAttribute
assertClassNotHasStaticAttribute 
by property_exists()
https://github.com/sebastianbergmann/phpunit/issues/4601

[PHPUnit10] Replace deleted PHPUnit methods

---

rules-tests/PHPUnit100/Rector/Class_/RemoveNamedArgsInDataProviderRector/Fixture/provide_data_with_multiple_yields.php.inc
rules-tests/PHPUnit100/Rector/Class_/RemoveNamedArgsInDataProviderRector/Fixture/provide_data_with_named_and_not_named_args.php.inc
rules-tests/PHPUnit100/Rector/Class_/RemoveNamedArgsInDataProviderRector/Fixture/provide_data_with_named_args.php.inc
rules-tests/PHPUnit100/Rector/Class_/RemoveNamedArgsInDataProviderRector/Fixture/provide_data_with_no_named_args.php.inc
rules-tests/PHPUnit100/Rector/Class_/RemoveNamedArgsInDataProviderRector/Fixture/provide_data_with_return.php.inc
rules-tests/PHPUnit100/Rector/Class_/RemoveNamedArgsInDataProviderRector/Fixture/provide_data_with_several_named_and_not_named_args.php.inc
rules-tests/PHPUnit100/Rector/Class_/RemoveNamedArgsInDataProviderRector/RemoveNamedArgsInDataProviderRectorTest.php
rules-tests/PHPUnit100/Rector/Class_/RemoveNamedArgsInDataProviderRector/config/configured_rule.php
rules/PHPUnit100/Rector/Class_/RemoveNamedArgsInDataProviderRector.php

Hi, according to #429 , I created a rule to remove the keys from the provided array in data provider methods.

Removed named args in data provides

---

rules-tests/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Fixture/covers_class.php.inc
rules-tests/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Fixture/covers_method.php.inc
rules/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector.php
rules/CodeQuality/Rector/FuncCall/AssertFuncCallToPHPUnitAssertRector.php
tests/Issues/DoubleAnnotation/Fixture/some_test.php.inc

The PHPUnit 9.6 `@covers` annotation supports specification of methods:
https://docs.phpunit.de/en/9.6/annotations.html#covers
That is:
```
/**
* @covers \someClass::someMethod
*/
```
The `CoversAnnotationWithValueToAttributeRector` conversion is currently unaware of this and converting it to a `CoversClass` attribute, that is:
```
#[\PHPUnit\Framework\Attributes\CoversClass(\someClass::someMethod)
```
This is, of course, a syntax error. It should create a `CoversMethod` attribute:
```
#[\PHPUnit\Framework\Attributes\CoversClass(\someClass::class, 'someMethod')
```
This patch changes the behaviour to look for a `::` in the annotation and, if found, grab the class and use the `CoversMethod` Attribute with the class and method name. The behaviour for an annotation that _starts_ with `::` is …

[AnnotationsToAttributes] Fix @covers qualified::method conversion

---

rules-tests/PHPUnit90/Rector/MethodCall/ReplaceAtMethodWithDesiredMatcherRector/Fixture/AtWithOneCount.php.inc
rules-tests/PHPUnit90/Rector/MethodCall/ReplaceAtMethodWithDesiredMatcherRector/Fixture/AtWithTwoOrMoreCount.php.inc
rules-tests/PHPUnit90/Rector/MethodCall/ReplaceAtMethodWithDesiredMatcherRector/Fixture/AtWithZeroCount.php.inc
rules-tests/PHPUnit90/Rector/MethodCall/ReplaceAtMethodWithDesiredMatcherRector/Fixture/MultipleAtWithDifferentCount.php.inc
rules-tests/PHPUnit90/Rector/MethodCall/ReplaceAtMethodWithDesiredMatcherRector/ReplaceAtMethodWithDesiredMatcherRectorTest.php
rules-tests/PHPUnit90/Rector/MethodCall/ReplaceAtMethodWithDesiredMatcherRector/config/configured_rule.php
rules/PHPUnit90/Rector/MethodCall/ReplaceAtMethodWithDesiredMatcherRector.php

Add the new ReplaceAtMethodWithDesiredMatcherRector rule

---

rules/PHPUnit90/Rector/MethodCall/ReplaceAtMethodWithDesiredMatcherRector.php

Ref https://github.com/rectorphp/rector-phpunit/pull/454#pullrequestreview-2588439166

[PHPUnit90] Ensure return node on has changed on ReplaceAtMethodWithDesiredMatcherRector

---

config/sets/phpunit-code-quality.php
rules-tests/CodeQuality/Rector/MethodCall/AssertCountWithZeroToAssertEmptyRector/AssertCountWithZeroToAssertEmptyRectorTest.php
rules-tests/CodeQuality/Rector/MethodCall/AssertCountWithZeroToAssertEmptyRector/Fixture/count_to_empty.php.inc
rules-tests/CodeQuality/Rector/MethodCall/AssertCountWithZeroToAssertEmptyRector/Fixture/skip_on_first_class_callable.php.inc
rules-tests/CodeQuality/Rector/MethodCall/AssertCountWithZeroToAssertEmptyRector/Fixture/skip_on_non_test_class.php.inc
rules-tests/CodeQuality/Rector/MethodCall/AssertCountWithZeroToAssertEmptyRector/Fixture/skip_on_non_zero_argument.php.inc
rules-tests/CodeQuality/Rector/MethodCall/AssertCountWithZeroToAssertEmptyRector/Source/Collection.php
rules-tests/CodeQuality/Rector/MethodCall/AssertCountWithZeroToAssertEmptyRector/config/configured_rule.php
rules/CodeQuality/Rector/MethodCall/AssertCountWithZeroToAssertEmptyRector.php

* Adds a new AssertCountWithZeroToAssertEmptyRector.
* Adds tests for the rule.
* Added to code quality set.
This is just a small but useful rector rule. It will convert use of `assertCount` with a first parameter of zero to be `assertEmpty`. Also handles the `not` use as well.
```diff
-$this->assertCount(0, $array);
+$this->assertEmpty($array);
-$this->assertNotCount(0, $array);
+$this->assertNotEmpty($array);
```

Adds AssertCountWithZeroToAssertEmptyRector rule

---

rules-tests/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Fixture/covers_trait.php.inc
rules-tests/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Source/ExistingTrait.php
rules/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector.php

Fixes https://github.com/rectorphp/rector/issues/9034

[Attribute] Add CoversTrait support on CoversAnnotationWithValueToAttributeRector

---

rules-tests/CodeQuality/Rector/ClassMethod/AddInstanceofAssertForNullableInstanceRector/Fixture/multiple_assert.php.inc
rules/CodeQuality/Rector/ClassMethod/AddInstanceofAssertForNullableInstanceRector.php

Ref https://github.com/rectorphp/rector-phpunit/pull/466#issuecomment-2762717039
Ref https://getrector.com/demo/b6a49070-ed48-44a0-885c-54dabbfdbf22
second assert is inserted before variable definition so cause undefined variable
```
Undefined variable $someObject2
```

[CodeQuality] Handle crash on multiple assert cause undefined variable on AddInstanceofAssertForNullableInstanceRector

---

rules-tests/CodeQuality/Rector/ClassMethod/AddInstanceofAssertForNullableInstanceRector/Fixture/add_instance_only_once.php.inc
rules-tests/CodeQuality/Rector/ClassMethod/AddInstanceofAssertForNullableInstanceRector/Fixture/call_on_nullable.php.inc
rules-tests/CodeQuality/Rector/ClassMethod/AddInstanceofAssertForNullableInstanceRector/Fixture/multiple_assert.php.inc
rules/CodeQuality/Rector/ClassMethod/AddInstanceofAssertForNullableInstanceRector.php

> Call to method PHPUnit\Framework\Assert::assertInstanceOf() with incorrect case: assertInstanceof

[CodeQuality] fix assertInstanceOf casing

---

rules-tests/PHPUnit90/Rector/MethodCall/SpecificAssertContainsWithoutIdentityRector/Fixture/skip_no_second_arg.php.inc
rules/PHPUnit90/Rector/MethodCall/SpecificAssertContainsWithoutIdentityRector.php
src/NodeAnalyzer/TestsNodeAnalyzer.php

Fixes https://github.com/rectorphp/rector/issues/9104
Ref https://getrector.com/demo/7a606a35-711f-4797-b1ef-eb293a19ca0d

[PHPUnit90] Handle crash on different object without second arg on SpecificAssertContainsWithoutIdentityRector

---

rules/PHPUnit100/Rector/Class_/RemoveNamedArgsInDataProviderRector.php

Ref https://github.com/rectorphp/rector-src/actions/runs/14168592413/job/40439865009?pr=6794

[PHPUnit100] Skip already key = null on RemoveNamedArgsInDataProviderRector

---

config/sets/phpunit100.php
rules-tests/PHPUnit100/Rector/Class_/ParentTestClassConstructorRector/Fixture/mocking_helper.php.inc
rules-tests/PHPUnit100/Rector/Class_/ParentTestClassConstructorRector/Fixture/skip_abstract_classes.php.inc
rules-tests/PHPUnit100/Rector/Class_/ParentTestClassConstructorRector/Fixture/skip_already_added.php.inc
rules-tests/PHPUnit100/Rector/Class_/ParentTestClassConstructorRector/Fixture/skip_in_case_of_test.php.inc
rules-tests/PHPUnit100/Rector/Class_/ParentTestClassConstructorRector/Fixture/skip_in_case_of_test_case.php.inc
rules-tests/PHPUnit100/Rector/Class_/ParentTestClassConstructorRector/ParentTestClassConstructorRectorTest.php
rules-tests/PHPUnit100/Rector/Class_/ParentTestClassConstructorRector/config/configured_rule.php
rules/PHPUnit100/Rector/Class_/ParentTestClassConstructorRector.php

Fixes BC break in case of non-test `TestCase` class use, ref https://github.com/sebastianbergmann/phpunit/commit/705874f1b867fd99865e43cb5eaea4e6d141582f
Ref https://github.com/sebastianbergmann/phpunit/issues/3975

[phpunit 10] Add ParentTestClassConstructorRector

---

config/sets/annotations-to-attributes.php
rules-tests/AnnotationsToAttributes/Rector/Class_/AnnotationWithValueToAttributeRector/Fixture/skip_uses_in_anonymous_class.php.inc
rules-tests/AnnotationsToAttributes/Rector/Class_/AnnotationWithValueToAttributeRector/Fixture/uses_in_test.php.inc
rules-tests/AnnotationsToAttributes/Rector/Class_/AnnotationWithValueToAttributeRector/config/configured_rule.php
rules/AnnotationsToAttributes/Rector/Class_/AnnotationWithValueToAttributeRector.php
src/ValueObject/AnnotationWithValueToAttribute.php

Make rule configurable to apply on class level.
Fixes https://github.com/rectorphp/rector/issues/9178

[AnnotationsToAttributes] Apply to class level on @uses on AnnotationWithValueToAttributeRector

---

config/sets/phpunit110.php
config/sets/phpunit120.php
rules-tests/PHPUnit120/Rector/Class_/RemoveOverrideFinalConstructTestCaseRector/Fixture/fixture.php.inc
rules-tests/PHPUnit120/Rector/Class_/RemoveOverrideFinalConstructTestCaseRector/RemoveOverrideFinalConstructTestCaseRectorTest.php
rules-tests/PHPUnit120/Rector/Class_/RemoveOverrideFinalConstructTestCaseRector/config/configured_rule.php
rules/PHPUnit100/Rector/Class_/ParentTestClassConstructorRector.php
rules/PHPUnit120/Rector/Class_/RemoveOverrideFinalConstructTestCaseRector.php
src/Set/PHPUnitSetList.php

- add phpunit 12 rule to remove `__construct` as already final
- use attribute flag `hasRemovedFinalConstruct` so in rule `ParentTestClassConstructorRector` can be checked to avoid flip flop change when both rules accidentally registered.
- Register missing phpunit 11 rule on config.
Fixes Closes https://github.com/rectorphp/rector/issues/9180

 [PHPUnit 12] Add RemoveOverrideFinalConstructTestCaseRector 

---

rules-tests/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector/Fixture/covers_class_default.php.inc
rules/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector.php

@TimelessTron this should ensure only remove when attribute group added.
Ref https://github.com/rectorphp/rector/issues/9183#issuecomment-2900116246

Only remove @covers when target exists

---

phpstan.neon
rules-tests/CodeQuality/Rector/Class_/TypeWillReturnCallableArrowFunctionRector/Fixture/skip_return_create_mock.php.inc
rules/CodeQuality/Rector/Class_/TypeWillReturnCallableArrowFunctionRector.php
rules/CodeQuality/Reflection/MethodParametersAndReturnTypesResolver.php
stubs/Symfony/Component/Form/FormInterface.php

@TomasVotruba I tested in our project, this cause diff:
```diff
1) Rector\PHPUnit\Tests\CodeQuality\Rector\Class_\TypeWillReturnCallableArrowFunctionRector\TypeWillReturnCallableArrowFunctionRectorTest::test with data set #3 ('/Users/samsonasik/www/rector-...hp.inc')
Failed on fixture file "skip_return_create_mock.php.inc"
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
$form = $this->createMock(FormInterface::class);
$form->method('add')
-            ->willReturnCallback(function ($name, $type, $options) use (&$calls) {
+            ->willReturnCallback(function ($name, $type, $options) use (&$calls): static {
$calls[] = compact('name', 'type', 'options');
return $this->createMock(FormInterface::class);
});
```
which cause error:
```diff
There was 1 …
```

[CodeQuality] Skip return createMock() on TypeWillReturnCallableArrowFunctionRector

---

phpstan.neon
rules-tests/CodeQuality/Rector/Class_/TypeWillReturnCallableArrowFunctionRector/Fixture/fill_known_param_type_object.php.inc
rules-tests/CodeQuality/Rector/Class_/TypeWillReturnCallableArrowFunctionRector/Source/SomeMockedClass.php
rules/CodeQuality/Reflection/MethodParametersAndReturnTypesResolver.php

It currently got error:
```
There was 1 error:
1) Rector\PHPUnit\Tests\CodeQuality\Rector\Class_\TypeWillReturnCallableArrowFunctionRector\TypeWillReturnCallableArrowFunctionRectorTest::test with data set #2 ('/Users/samsonasik/www/rector-...hp.inc')
Error: Call to undefined method PHPStan\Type\ObjectWithoutClassType::getClassReflection()
/Users/samsonasik/www/rector-phpunit/rules/CodeQuality/Reflection/MethodParametersAndReturnTypesResolver.php:68
```

[CodeQuality] Handle crash on native "object" type on TypeWillReturnCallableArrowFunctionRector

---

rules-tests/CodeQuality/Rector/Class_/AddParamTypeFromDependsRector/Fixture/skip_no_depends.php.inc
rules/CodeQuality/Rector/Class_/AddParamTypeFromDependsRector.php

Fixes https://github.com/rectorphp/rector-phpunit/issues/536

[CodeQuality] Handle crash on no @depends on AddParamTypeFromDependsRector
