rectorphp/rector-phpunit

src/Rector/Class_/ArrayArgumentToDataProviderRector.php
src/Rector/MethodCall/AssertIssetToSpecificMethodRector.php
tests/Rector/MethodCall/AssertIssetToSpecificMethodRector/Fixture/magic_method_set_is_ignored.php.inc
tests/Rector/MethodCall/AssertIssetToSpecificMethodRector/Fixture/skip.php.inc
tests/Rector/MethodCall/AssertIssetToSpecificMethodRector/Fixture/skip_if_magic_method_isset_exists.php.inc

Fixes https://github.com/rectorphp/rector-phpunit/issues

added failing test case + fix

---

src/NodeAnalyzer/TestsNodeAnalyzer.php

Fix regression of https://github.com/rectorphp/rector-phpunit/commit/46610e19c684a8e87ebeb00c6d29af0a6932ae69

[NodeAnalyzer] Fixing regression on class node get

---

src/NodeFactory/ExpectExceptionMethodCallFactory.php
src/PhpDoc/PhpDocValueToNodeMapper.php
tests/Rector/ClassMethod/ExceptionAnnotationRector/Fixture/fixture5.php.inc
tests/Rector/ClassMethod/ExceptionAnnotationRector/Fixture/fixture6.php.inc

[PHPUnit] Handle SomeClass::someMethod in message reference string

---

composer.json
src/Rector/Foreach_/SimplifyForeachInstanceOfRector.php

Fixes found bugs in https://github.com/rectorphp/rector-src/pull/1297

Scope refresh fixes

---

composer.json
config/sets/phpunit-code-quality.php
config/sets/phpunit-exception.php
config/sets/phpunit-yield-data-provider.php
config/sets/phpunit40.php
config/sets/phpunit60.php
config/sets/phpunit70.php
config/sets/phpunit80.php
config/sets/phpunit90.php
config/sets/phpunit91.php
docs/rector_rules_overview.md
patches/symfony-dependency-injection-loader-configurator-servicesconfigurator-php.patch
tests/Rector/Class_/ArrayArgumentToDataProviderRector/config/configured_rule.php

Ref https://github.com/rectorphp/rector-src/pull/1344

[DX] Make use of configure() method

---

tests/Rector/ClassMethod/MigrateAtToConsecutiveExpectationsRector/Fixture/ignoring_with.php.inc
tests/Rector/ClassMethod/MigrateAtToConsecutiveExpectationsRector/Fixture/ignoring_with_complex.php.inc
tests/Rector/ClassMethod/MigrateAtToConsecutiveExpectationsRector/Fixture/mixing_arrays.php.inc

Add fixture for https://getrector.org/demo/1ec84192-9d46-65fc-947d-9f7ed7e29daf as discussed in https://github.com/rectorphp/rector/issues/6976#issuecomment-1027831779.

[WIP] MigrateAtToConsecutiveExpectationsRector skips some cases

---

src/Rector/ClassMethod/ReplaceTestAnnotationWithPrefixedFunctionRector.php
tests/Rector/ClassMethod/ReplaceTestAnnotationWithPrefixedFunctionRector/Fixture/fixture.php.inc
tests/Rector/ClassMethod/ReplaceTestAnnotationWithPrefixedFunctionRector/Fixture/skip_already_prefixed_function.php.inc
tests/Rector/ClassMethod/ReplaceTestAnnotationWithPrefixedFunctionRector/Fixture/skip_missing_test_annotation.php.inc
tests/Rector/ClassMethod/ReplaceTestAnnotationWithPrefixedFunctionRector/ReplaceTestAnnotationWithPrefixedFunctionRectorTest.php
tests/Rector/ClassMethod/ReplaceTestAnnotationWithPrefixedFunctionRector/config/configured_rule.php

closes https://github.com/rectorphp/rector-phpunit/issues/45

Convert test annotation to test prefix

---

src/NodeAnalyzer/AssertCallAnalyzer.php
tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Fixture/skip_prophecy_should.php.inc

fixes https://github.com/rectorphp/rector/issues/7107

Fix unexpected doesNotPerformAssertions for tests with prophecy should

---

config/config.php
config/sets/level/up-to-phpunit-100.php
config/sets/level/up-to-phpunit-50.php
config/sets/level/up-to-phpunit-60.php
config/sets/level/up-to-phpunit-70.php
config/sets/level/up-to-phpunit-80.php
config/sets/level/up-to-phpunit-90.php
config/sets/phpunit-code-quality.php
config/sets/phpunit-exception.php
config/sets/phpunit-mock.php
config/sets/phpunit-specific-method.php
config/sets/phpunit-yield-data-provider.php
config/sets/phpunit40.php
config/sets/phpunit50.php
config/sets/phpunit60.php
config/sets/phpunit70.php
config/sets/phpunit75.php
config/sets/phpunit80-dms.php
config/sets/phpunit80.php
config/sets/phpunit90.php
config/sets/phpunit91.php
ecs.php
rector.php

Ref https://github.com/rectorphp/rector-src/pull/2065#issue-1201810126

[DX] Use RectorConfig instead of ContainerConfigurator

---

src/NodeAnalyzer/IdentifierManipulator.php
src/Rector/MethodCall/AssertEqualsToSameRector.php
src/Rector/MethodCall/AssertFalseStrposToContainsRector.php
src/Rector/MethodCall/AssertPropertyExistsRector.php
tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/config/configured_rule.php
tests/Rector/Class_/AddSeeTestAnnotationRector/config/configured_rule.php
tests/Rector/Class_/RemoveDataProviderTestPrefixRector/config/configured_rule.php
tests/Rector/MethodCall/AssertEqualsToSameRector/Fixture/mark_test_incomplete.php.inc
tests/Rector/MethodCall/AssertEqualsToSameRector/config/configured_rule.php
tests/Rector/MethodCall/SpecificAssertInternalTypeRector/config/configured_rule.php

Depends on https://github.com/rectorphp/rector-src/pull/2239

Make Rector rules work with scope refresh

---

src/NodeAnalyzer/AssertCallAnalyzer.php
tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Fixture/skip_do_test_file_info.php.inc

As suggested in: https://github.com/rectorphp/rector-src/pull/2303
Closes https://github.com/rectorphp/rector-src/pull/2303

Add rector doTestFileInfo to the excluded method names

---

phpstan.neon
src/Rector/StaticCall/GetMockRector.php
tests/Rector/StaticCall/GetMockRector/Fixture/skip_private_get_mock.php.inc

Closes https://github.com/rectorphp/rector-phpunit/issues/76

Skip local getMock() method on GetMockRector

---

tests/Rector/StaticCall/GetMockRector/Fixture/skip_exception_get_mock.php.inc
tests/Rector/StaticCall/GetMockRector/Source/SomeExceptionWithGetMock.php

Second fixture for https://github.com/rectorphp/rector-phpunit/issues/76

Add second fixture, just in case

---

tests/Rector/MethodCall/SpecificAssertContainsRector/Fixture/skip_array_map.php.inc

Ref https://github.com/rectorphp/rector-phpunit/pull/73

add array_map fixture in SpecificAssertContainsRector

---

src/Rector/MethodCall/GetMockBuilderGetMockToCreateMockRector.php
tests/Rector/MethodCall/GetMockBuilderGetMockToCreateMockRector/Fixture/only_methods.php.inc
tests/Rector/MethodCall/GetMockBuilderGetMockToCreateMockRector/Fixture/set_methods.php.inc

Closes https://github.com/rectorphp/rector-phpunit/issues/74

Extends GetMockBuilderGetMockToCreateMockRector with only methods

---

src/NodeAnalyzer/AssertCallAnalyzer.php
src/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector.php
tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Fixture/keep_with_mulitiple_function_calls.php.inc

Closes https://github.com/rectorphp/rector/issues/7421

Fix Doesnotperformassert rule by increasing the nesting level to 5

---

src/Rector/ClassMethod/CreateMockToAnonymousClassRector.php
tests/Rector/ClassMethod/CreateMockToAnonymousClassRector/Fixture/skip_with_args.php.inc

Follow up to https://github.com/rectorphp/rector-phpunit/pull/111

Only change if there is a variale defined

---

docs/rector_rules_overview.md
src/Rector/MethodCall/SpecificAssertContainsRector.php

Add rector rules CreateMockToAnonymousClassRector, ProphecyPHPDocRector and UseSpecificWithMethodRector to docs

Add rector rules to docs

---

src/Rector/MethodCall/AssertEqualsToSameRector.php
tests/Rector/MethodCall/AssertEqualsToSameRector/Fixture/skip_if_an_object_is_in_any_level_of_an_array.php.inc

Closes https://github.com/rectorphp/rector-phpunit/pull/121

[PHPUnit] Skip AssertEqualsToSameRector on array with value with non-scalar in any level

---

config/sets/phpunit100.php
src/NodeFinder/DataProviderClassMethodFinder.php
src/PhpDoc/DataProviderMethodRenamer.php
src/Rector/Class_/RemoveDataProviderTestPrefixRector.php
src/Rector/Class_/StaticDataProviderClassMethodRector.php
src/Set/PHPUnitSetList.php
tests/Rector/Class_/StaticDataProviderClassMethodRector/Fixture/cover_no_bracket_name.php.inc
tests/Rector/Class_/StaticDataProviderClassMethodRector/Fixture/multiple_data_providers.php.inc
tests/Rector/Class_/StaticDataProviderClassMethodRector/Fixture/skip_already_static.php.inc
tests/Rector/Class_/StaticDataProviderClassMethodRector/Fixture/some_class.php.inc
tests/Rector/Class_/StaticDataProviderClassMethodRector/StaticDataProviderClassMethodRectorTest.php
tests/Rector/Class_/StaticDataProviderClassMethodRector/config/configured_rule.php

Closes https://github.com/rectorphp/rector-phpunit/issues/126

[PHPUnit 10.0] Add StaticDataProviderClassMethodRector

---

config/sets/annotations-to-attributes.php
src/Rector/Class_/AnnotationWithValueToAttributeRector.php
src/ValueObject/AnnotationWithValueToAttribute.php
tests/Rector/Class_/AnnotationWithValueToAttributeRector/Fixture/with_a_data_provider.php.inc
tests/Rector/Class_/AnnotationWithValueToAttributeRector/config/configured_rule.php

* Ref https://github.com/rectorphp/rector-phpunit/issues/69
* Ref https://github.com/sebastianbergmann/phpunit/issues/4502
Follow up to https://github.com/rectorphp/rector-phpunit/pull/129

[PHPUnit 10] Extends annotation to attribute set

---

src/Rector/ClassMethod/DependsAnnotationWithValueToAttributeRector.php
tests/Rector/ClassMethod/DependsAnnotationWithValueToAttributeRector/Fixture/depends_on_class.php.inc

@depends on class should use `PHPUnit\Framework\Attributes\DependsOnClass`

[PHPUnit] Fix @depends on class should use DependsOnClass attribute

---

src/Rector/ClassMethod/DataProviderAnnotationToAttributeRector.php
tests/Rector/ClassMethod/DataProviderAnnotationToAttributeRector/Fixture/external-provider-fqcn.php.inc
tests/Rector/ClassMethod/DataProviderAnnotationToAttributeRector/Fixture/external-provider.php.inc

closes https://github.com/rectorphp/rector/issues/7876

Use `#[DataProviderExternal]` instead of `#[DataProvider]` attribute

---

composer.json
config/sets/phpunit-specific-method.php
rector.php
src/Rector/MethodCall/AssertFalseStrposToContainsRector.php
tests/Rector/MethodCall/AssertFalseStrposToContainsRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/AssertFalseStrposToContainsRector/Fixture/string_contains_string.php.inc

Closes https://github.com/rectorphp/rector/issues/7625

Make AssertFalseStrposToContainsRector use assertStringContainsString methods

---

src/NodeAnalyzer/TestsNodeAnalyzer.php

Use `ReflectionResolver` instead.

[NodeAnalyzer] Remove parent attribute on TestsNodeAnalyzer

---

src/Rector/Class_/ArrayArgumentToDataProviderRector.php

https://github.com/rectorphp/rector/issues/7947

 Remove parent lookup on ArrayArgumentToDataProviderRector 

---

docs/rector_rules_overview.md
src/NodeAnalyzer/IdentifierManipulator.php
src/NodeFinder/DataProviderClassMethodFinder.php
src/Rector/Class_/PreferPHPUnitThisCallRector.php
tests/Rector/Class_/PreferPHPUnitThisCallRector/Fixture/skip_replace_in_static_call.php.inc

fixes [#8008](https://github.com/rectorphp/rector/issues/8008)

[PreferPHPUnitThisCallRector] Make sure to skip static funct fixes #8008

---

src/Rector/ClassMethod/TryCatchToExpectExceptionRector.php
tests/Rector/ClassMethod/TryCatchToExpectExceptionRector/Fixture/issue199.php.inc

Correct behavior of `TryCatchToExpectExceptionRector`

---

src/Rector/MethodCall/AssertTrueFalseToSpecificMethodRector.php
tests/Rector/MethodCall/AssertTrueFalseToSpecificMethodRector/Fixture/demo_file2_test.php.inc
tests/Rector/MethodCall/AssertTrueFalseToSpecificMethodRector/Fixture/demo_file_test.php.inc

Correct behavior of `AssertTrueFalseToSpecificMethodRector`

---

config/sets/level/up-to-phpunit-91.php
src/Set/PHPUnitLevelSetList.php

There exists a `PHPUnitSetList::PHPUNIT_91` but not a `PHPUnitLevelSetList::UP_TO_PHPUNIT_91`.

Add PHPUnitLevelSetList::UP_TO_PHPUNIT_91 ruleset

---

src/Rector/Class_/CoversAnnotationWithValueToAttributeRector.php
tests/Issues/DoubleAnnotation/DoubleAnnotationTest.php
tests/Issues/DoubleAnnotation/Fixture/some_test.php.inc
tests/Issues/DoubleAnnotation/config/configured_rule.php

Fixes https://github.com/rectorphp/rector/issues/8038

Fix double merge of attributes

---

composer.json
config/sets/annotations-to-attributes.php
config/sets/level/up-to-phpunit-91.php
config/sets/phpunit100.php
phpstan.neon
rector.php
rules-tests/AnnotationsToAttributes/Rector/ClassMethod/TestWithAnnotationToAttributeRector/Fixture/some_fixture.php.inc
rules-tests/AnnotationsToAttributes/Rector/ClassMethod/TestWithAnnotationToAttributeRector/Fixture/some_lower_cased.php.inc
rules-tests/AnnotationsToAttributes/Rector/ClassMethod/TestWithAnnotationToAttributeRector/Fixture/the_most_complex_json.php.inc
rules-tests/AnnotationsToAttributes/Rector/ClassMethod/TestWithAnnotationToAttributeRector/TestWithAnnotationToAttributeRectorTest.php
rules-tests/AnnotationsToAttributes/Rector/ClassMethod/TestWithAnnotationToAttributeRector/config/configured_rule.php
rules/AnnotationsToAttributes/Rector/ClassMethod/TestWithAnnotationToAttributeRector.php

Closes https://github.com/rectorphp/rector-phpunit/issues/191

[PHPUnit 10] Add TestWithAnnotationToAttributeRector

---

src/NodeAnalyzer/AssertCallAnalyzer.php
src/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector.php
tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Fixture/skip_method_call_with_mock_property.php.inc

Fixes https://github.com/rectorphp/rector-phpunit/issues/165

Add mocked property in another class method check

---

.gitattributes

To avoid included in rector/rector scoped https://github.com/rectorphp/rector/commit/50d0f997c681e8c27ee0702a2c756983bcc104e1#diff-7d3ddf4211e87062c50a8572776528ffdde8b0d9afd98e53b5b8484ffbea611a

Register rules-tests to .gitattributes

---

tests/Issues/RectorOrder/Fixture/some_test.php.inc
tests/Issues/RectorOrder/RectorOrderTest.php
tests/Issues/RectorOrder/config/configured_rule.php

Ref https://github.com/rectorphp/rector-src/pull/4496

Move core RectorOrder test here

---

config/sets/level/up-to-phpunit-91.php
config/sets/phpunit91.php
src/Set/PHPUnitLevelSetList.php

See https://github.com/rectorphp/rector-phpunit/pull/236#discussion_r1266717750 i saw i forgot a few more

[PHPUnitSetList] Update reference for deprecated constant

---

rules-tests/PHPUnit100/Rector/Class_/AddProphecyTraitRector/Fixture/skip_if_already_added_in_parent_class.php.inc
rules-tests/PHPUnit100/Rector/Class_/AddProphecyTraitRector/Source/ParentClassWithPropertyTrait.php
rules/PHPUnit100/Rector/Class_/AddProphecyTraitRector.php

Closes https://github.com/rectorphp/rector/issues/8074

Skip AddProphecyTraitRector if parent class already has the trait

---

composer.json
config/sets/phpunit100.php
docs/rector_rules_overview.md
phpstan.neon
src/Rector/StmtsAwareInterface/WithConsecutiveRector.php
tests/Rector/ClassMethod/CreateMockToAnonymousClassRector/Fixture/mocked_more_methods.php
tests/Rector/StmtsAwareInterface/WithConsecutiveRector/Fixture/some_class.php.inc
tests/Rector/StmtsAwareInterface/WithConsecutiveRector/WithConsecutiveRectorTest.php
tests/Rector/StmtsAwareInterface/WithConsecutiveRector/config/configured_rule.php

Ref https://stackoverflow.com/a/75686291/1348344

[PHPUnit 10] Add WithConsecutiveRector

---

src/Rector/Class_/PreferPHPUnitSelfCallRector.php

counterpart of https://github.com/rectorphp/rector-src/pull/4951

PreferPHPUnitSelfCallRector: use NodeNameResolver->matchesStringName()

---

src/Rector/StmtsAwareInterface/WithConsecutiveRector.php
tests/Rector/StmtsAwareInterface/WithConsecutiveRector/Fixture/some_class.php.inc

Closes https://github.com/rectorphp/rector-phpunit/issues/268

Fix withConsecutive() method name

---

composer.json
rules/AnnotationsToAttributes/Rector/ClassMethod/TestWithAnnotationToAttributeRector.php
rules/AnnotationsToAttributes/Rector/Class_/CoversAnnotationWithValueToAttributeRector.php
rules/CodeQuality/Rector/Class_/ConstructClassMethodToSetUpTestCaseRector.php
rules/CodeQuality/Rector/Class_/YieldDataProviderRector.php
rules/CodeQuality/Rector/MethodCall/AssertComparisonToSpecificMethodRector.php
rules/CodeQuality/Rector/MethodCall/AssertFalseStrposToContainsRector.php
rules/CodeQuality/Rector/MethodCall/AssertInstanceOfComparisonRector.php
rules/CodeQuality/Rector/MethodCall/AssertIssetToSpecificMethodRector.php
rules/CodeQuality/Rector/MethodCall/AssertRegExpRector.php
rules/CodeQuality/Rector/MethodCall/AssertTrueFalseToSpecificMethodRector.php
rules/PHPUnit60/Rector/ClassMethod/ExceptionAnnotationRector.php
src/NodeFinder/DataProviderClassMethodFinder.php

after I update packages locally new rules was applied.

New fix after run rector

---

config/sets/phpunit-code-quality.php
rules-tests/CodeQuality/Rector/Class_/TestWithToDataProviderRector/Fixture/fixture.php.inc
rules-tests/CodeQuality/Rector/Class_/TestWithToDataProviderRector/Fixture/fixture2_array.php.inc
rules-tests/CodeQuality/Rector/Class_/TestWithToDataProviderRector/Fixture/fixture3_different_values.php.inc
rules-tests/CodeQuality/Rector/Class_/TestWithToDataProviderRector/Fixture/fixture4_test_annotation.php.inc
rules-tests/CodeQuality/Rector/Class_/TestWithToDataProviderRector/Fixture/fixture5_multiple_test.php.inc
rules-tests/CodeQuality/Rector/Class_/TestWithToDataProviderRector/TestWithToDataProviderRectorTest.php
rules-tests/CodeQuality/Rector/Class_/TestWithToDataProviderRector/config/configured_rule.php
rules/CodeQuality/Rector/Class_/TestWithToDataProviderRector.php

Feature/replace testWith annotation to dataProviders

---

rules-tests/CodeQuality/Rector/Class_/TestWithToDataProviderRector/Fixture/fixture.php.inc
rules/CodeQuality/Rector/Class_/TestWithToDataProviderRector.php

Hello, I did not realise that is possible to use `testWith multiline`.
I adjust the code to work with this
Close #281

Support testWith multiline

---

rules-tests/CodeQuality/Rector/MethodCall/UseSpecificWillMethodRector/Fixture/will_return_map_object.php.inc
rules/CodeQuality/Rector/MethodCall/UseSpecificWillMethodRector.php

- add fixture
- add New value map support

Add return map value object support to UseSpecificWillMethodRector

---

rules-tests/CodeQuality/Rector/MethodCall/AssertRegExpRector/Fixture/skip_used_by_next_stmt.php.inc
rules/CodeQuality/Rector/MethodCall/AssertRegExpRector.php

Fixes https://github.com/rectorphp/rector/issues/8669

[CodeQuality] Skip AssertRegExpRector on matches variable used in next stmt

---

rules/AnnotationsToAttributes/Rector/Class_/TicketAnnotationToAttributeRector.php

Fixes https://github.com/rectorphp/rector/issues/8790

[Prefix] Fix Prefixed PHPUnit Ticket class

---

rules-tests/CodeQuality/Rector/Class_/AddParentSetupCallOnSetupRector/AddParentSetupCallOnSetupRectorTest.php
rules-tests/CodeQuality/Rector/Class_/AddParentSetupCallOnSetupRector/Fixture/missing_setup.php.inc
rules-tests/CodeQuality/Rector/Class_/AddParentSetupCallOnSetupRector/Fixture/missing_setup_with_other_stmt.php.inc
rules-tests/CodeQuality/Rector/Class_/AddParentSetupCallOnSetupRector/Fixture/skip_setup_exists.php.inc
rules-tests/CodeQuality/Rector/Class_/AddParentSetupCallOnSetupRector/config/configured_rule.php
rules/CodeQuality/Rector/Class_/AddParentSetupCallOnSetupRector.php

Closes https://github.com/rectorphp/rector-phpunit/issues/361

 [CodeQuality] Add AddParentSetupCallOnSetupRector 

---

config/sets/phpunit-code-quality.php
rules-tests/CodeQuality/Rector/MethodCall/SingleWithConsecutiveToWithRector/Fixture/repeated_same.php.inc
rules-tests/CodeQuality/Rector/MethodCall/SingleWithConsecutiveToWithRector/Fixture/skip_multiple_values.php.inc
rules-tests/CodeQuality/Rector/MethodCall/SingleWithConsecutiveToWithRector/SingleWithConsecutiveToWithRectorTest.php
rules-tests/CodeQuality/Rector/MethodCall/SingleWithConsecutiveToWithRector/Source/SomeMockedClass.php
rules-tests/CodeQuality/Rector/MethodCall/SingleWithConsecutiveToWithRector/config/configured_rule.php
rules/CodeQuality/Rector/MethodCall/SingleWithConsecutiveToWithRector.php

Follow up to https://github.com/rectorphp/rector-phpunit/pull/369

[CodeQuality] Add SingleWithConsecutiveToWithRector

---

config/sets/phpunit-code-quality.php
rules-tests/CodeQuality/Rector/MethodCall/NarrowIdenticalWithConsecutiveRector/Fixture/will_return_on_consecutive_calls.php.inc
rules-tests/CodeQuality/Rector/MethodCall/SingleWithConsecutiveToWithRector/Fixture/will_return_the_same.php.inc
rules/CodeQuality/Rector/MethodCall/NarrowIdenticalWithConsecutiveRector.php
rules/CodeQuality/Rector/MethodCall/SingleWithConsecutiveToWithRector.php

Follow up to https://github.com/rectorphp/rector-phpunit/pull/370

Add will return on consecutive support

---

rules-tests/PHPUnit100/Rector/StmtsAwareInterface/WithConsecutiveRector/Fixture/with_array_spread.php.inc
rules/PHPUnit100/Rector/StmtsAwareInterface/WithConsecutiveRector.php
src/NodeFactory/WithConsecutiveMatchFactory.php

- **fix static method name**
- **fix array dim fetch**

tv with consecutive 5

---

rules-tests/CodeQuality/Rector/MethodCall/NarrowIdenticalWithConsecutiveRector/Fixture/skip_unwrap.php.inc
rules-tests/CodeQuality/Rector/MethodCall/SingleWithConsecutiveToWithRector/Fixture/skip_unwrap.php.inc
rules-tests/CodeQuality/Rector/MethodCall/SingleWithConsecutiveToWithRector/Fixture/with_assert_inside.php.inc
rules/CodeQuality/Rector/MethodCall/NarrowIdenticalWithConsecutiveRector.php
rules/CodeQuality/Rector/MethodCall/SingleWithConsecutiveToWithRector.php

- **skip unpack**
- **unwrap assert inside**
- **Add unwrap for instanceof checks**

tv skip variadic

---

rules-tests/CodeQuality/Rector/MethodCall/AssertCountWithZeroToAssertEmptyRector/Fixture/skip_union_type.php.inc
rules/CodeQuality/Rector/MethodCall/AssertCountWithZeroToAssertEmptyRector.php

Fixes https://github.com/rectorphp/rector-phpunit/issues/458

[CodeQuality] Skip union type on AssertCountWithZeroToAssertEmptyRector

---

src/NodeAnalyzer/TestsNodeAnalyzer.php

Ref 
- https://github.com/rectorphp/rector-src/pull/6775

Change deprecated ClassReflection::isSubClassOf() to ClassReflection::is() for PHPStan ^2.1.8

---

rules-tests/CodeQuality/Rector/Class_/PreferPHPUnitSelfCallRector/Fixture/skip_different_object.php.inc
rules-tests/CodeQuality/Rector/Class_/PreferPHPUnitThisCallRector/Fixture/skip_different_object.php.inc
rules/CodeQuality/NodeAnalyser/AssertMethodAnalyzer.php

Fixes https://github.com/rectorphp/rector/issues/9135

[PhpUnit] Skip different object on PreferPHPUnit(This/Self)CallRector

---

rules/CodeQuality/Rector/Class_/ConstructClassMethodToSetUpTestCaseRector.php
rules/PHPUnit100/Rector/Class_/StaticDataProviderClassMethodRector.php
rules/PHPUnit100/Rector/StmtsAwareInterface/ExpectsMethodCallDecorator.php

Ref PR:
- https://github.com/rectorphp/rector-src/pull/6875

Directly use isName(s) and getName() on rector rules

---

rector.php
rules/PHPUnit100/Rector/Class_/RemoveNamedArgsInDataProviderRector.php

in php-parser 5, ArrayItem is under Node.

Update to use ArrayItem under Node

---

rules-tests/AnnotationsToAttributes/Rector/ClassMethod/DataProviderAnnotationToAttributeRector/Fixture/already_in_use.php.inc
rules/AnnotationsToAttributes/Rector/ClassMethod/DataProviderAnnotationToAttributeRector.php

Ref https://github.com/rectorphp/rector-phpunit/pull/523#pullrequestreview-3155040664

Fix target method on dataProvider on DataProviderAnnotationToAttributeRector

---

rules/CodeQuality/Rector/Class_/AddReturnTypeToDependedRector.php

Ref https://github.com/rectorphp/rector-phpunit/pull/528#pullrequestreview-3174008146

Remove unused check return with expr as already covered on ReturnAnalyzer

---

rules/CodeQuality/Reflection/MethodParametersAndReturnTypesResolver.php

Ref https://github.com/rectorphp/rector-phpunit/pull/533#pullrequestreview-3181771056

[CodeQuality] Use getNativeMethod on MethodParametersAndReturnTypesResolver

---

rules/PHPUnit80/Rector/MethodCall/SpecificAssertContainsRector.php
rules/PHPUnit90/Rector/MethodCall/SpecificAssertContainsWithoutIdentityRector.php

PHPStan 2.1.23 just released and this PR fix phpstan notice
https://github.com/phpstan/phpstan/releases/tag/2.1.23

Fix PHPStan notice on PHPStan 2.1.23
